### ISSUE TITLE
Indent nested tables

### ISSUE THREAD

**Issue by RubixDev** [dprint/dprint-plugin-toml#15]
It is quite common to indent nested tables to make it visually clearer that they are "children". Currently this plugin removes the indent. It would be nice if it could either preserve it or even add an option to automatically add it if not present.

```toml
[[list-entry]]
key = 1

  [list-entry.subtable]
  key = 2
```
